server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=financeiro

jwt.secret=teste123
jwt.expiration=3600000

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger
